resolver: lts-16.20
packages:
- http-client
- http-client-tls
- http-client-openssl
- http-conduit
extra-deps:
- HsOpenSSL-0.11.4.20
- HsOpenSSL-x509-system-0.1.0.4
- crypton-0.31
- crypton-connection-0.3.1
- crypton-x509-1.7.6
- crypton-x509-store-1.6.9
- crypton-x509-system-1.6.7
- crypton-x509-validation-1.6.12
- tls-1.7.0
