jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack-lts-11:
        BUILD: stack
        ARGS: "--resolver lts-11"
      stack-lts-12:
        BUILD: stack
        ARGS: "--resolver lts-12"
      stack-lts-14:
        BUILD: stack
        ARGS: "--resolver lts-14"
    maxParallel: 6
  steps:
  - bash: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/

      # Missing C libraries on Windows
      grep -v openssl < stack.yaml > tmp
      mv tmp stack.yaml

      stack setup $ARGS > /dev/null
      stack --install-ghc $ARGS test --bench --only-dependencies
      # Don't run tests on Windows since they're unreliable. Hopefully fix in the future.
      stack $ARGS test --bench --no-run-benchmarks --no-run-tests
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Installation ${{parameters.os}} & Test'
